Repository nucleos/NucleosProfileBundle, pull requests merged in 2021-02, with the labels that each got.

#196 Fix DI for ConfirmRegistrationAction
  src/Resources/config/registration.php
Labels: bugfix

#197 Use laminas/automatic-releases
  .github/release-drafter.yml
  .github/workflows/automatic-release.yml
  .github/workflows/release-drafter.yml
  .github/workflows/remove-automerge.yml
Labels: automerge

#227 Remove changelog linker
  vendor-bin/tools/composer.json
  vendor-bin/tools/composer.lock
Labels: automerge

#224 Fix build trigger
  .github/workflows/continuous-integration.yml
  .github/workflows/documentation.yml
Labels: automerge

#235 Fix bundle class name.
  docs/installation.rst
Labels: Documentation
