Repository nucleos/NucleosProfileBundle, pull requests merged in 2021-03, with the labels that each got.

#238 Add a French translation for the bundle
  src/Resources/translations/NucleosProfileBundle.fr.yml
Labels: Enhancement

#241 Fix the mail class used for registration
  src/Mailer/Mailer.php
Labels: Bug

#252 Fix docs build
  .github/workflows/documentation.yml
Labels: automerge
